package tv.safetubeforkids.app.playback

import android.net.Uri
import androidx.media3.common.MediaItem
import androidx.media3.common.MediaMetadata
import androidx.media3.common.MimeTypes
import androidx.media3.common.util.UnstableApi
import androidx.media3.datasource.DefaultHttpDataSource
import androidx.media3.exoplayer.dash.DashMediaSource
import androidx.media3.exoplayer.source.MediaSource
import androidx.media3.exoplayer.source.MergingMediaSource
import androidx.media3.exoplayer.source.ProgressiveMediaSource

/**
 * Builds Media3 media items and sources for a resolved video.
 *
 * Preferred path is DASH: a single manifest that exposes several video and audio renditions,
 * which is what makes real quality/audio switching via Media3's track selection possible.
 * When no manifest is available the player falls back to a progressive stream, with a
 * video-only stream merged with the best audio stream when necessary.
 */
@androidx.annotation.OptIn(UnstableApi::class)
object PlayerMedia {

    const val USER_AGENT =
        "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:128.0) Gecko/20100101 Firefox/128.0"

    fun dataSourceFactory(): DefaultHttpDataSource.Factory = DefaultHttpDataSource.Factory()
        .setUserAgent(USER_AGENT)
        .setConnectTimeoutMs(15_000)
        .setReadTimeoutMs(15_000)
        .setAllowCrossProtocolRedirects(true)

    /** Media item carrying the video id, its title and any subtitle tracks. */
    fun mediaItem(media: ResolvedMedia, uri: Uri, captions: List<CaptionOption>): MediaItem {
        val subtitleConfigurations = captions.map { caption ->
            MediaItem.SubtitleConfiguration.Builder(Uri.parse(caption.url))
                .setMimeType(MimeTypes.APPLICATION_TTML)
                .setLanguage(caption.languageTag)
                .setLabel(if (caption.isAutoGenerated) "${caption.label} (auto)" else caption.label)
                .setSelectionFlags(0)
                .build()
        }
        return MediaItem.Builder()
            .setUri(uri)
            .setMediaId(media.videoId)
            .setMediaMetadata(MediaMetadata.Builder().setTitle(media.title).build())
            .setSubtitleConfigurations(subtitleConfigurations)
            .build()
    }

    /**
     * @param preferDash false forces the progressive path (used as the retry-after-failure route).
     */
    fun mediaSource(
        media: ResolvedMedia,
        quality: QualityOption?,
        audio: AudioOption?,
        preferDash: Boolean,
        captions: List<CaptionOption> = media.captions,
    ): MediaSource {
        val factory = dataSourceFactory()
        val dashUrl = media.dashMpdUrl

        if (preferDash && !dashUrl.isNullOrBlank()) {
            val item = mediaItem(media, Uri.parse(dashUrl), captions)
            return DashMediaSource.Factory(factory).createMediaSource(item)
        }

        val selected = quality ?: media.defaultQuality
            ?: throw IllegalStateException("No playable rendition for ${media.videoId}")
        val audioUrl = audio?.url ?: selected.audioUrl

        val videoItem = mediaItem(media, Uri.parse(selected.videoUrl), captions)
        val videoSource = ProgressiveMediaSource.Factory(factory).createMediaSource(videoItem)

        if (audioUrl.isNullOrBlank()) {
            // Progressive stream already contains its audio track.
            return videoSource
        }

        val audioItem = MediaItem.Builder()
            .setUri(Uri.parse(audioUrl))
            .setMediaId("${media.videoId}:audio")
            .build()
        val audioSource = ProgressiveMediaSource.Factory(factory).createMediaSource(audioItem)
        return MergingMediaSource(videoSource, audioSource)
    }
}
