package tv.safetubeforkids.app.playback

import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.withContext
import org.schabi.newpipe.extractor.ServiceList
import tv.safetubeforkids.app.util.AppLogger

/** One selectable video rendition. [audioUrl] is set when the video stream carries no audio. */
data class QualityOption(
    val height: Int,
    val label: String,
    val videoUrl: String,
    val audioUrl: String?,
    val isMerged: Boolean,
)

/**
 * One selectable audio track.
 *
 * YouTube publishes multi-language audio as separate tracks (English, Hindi, ...), each with its
 * own bitrate variants. A track - not a bitrate - is what a viewer chooses, so the bitrate
 * variants of one language collapse into a single option here.
 */
data class AudioOption(
    val label: String,
    val url: String,
    val bitrateKbps: Int,
    val trackId: String,
    val languageTag: String,
    val isAutoDubbed: Boolean = false,
)

/** One selectable subtitle track, already carrying YouTube's TTML URL. */
data class CaptionOption(
    val label: String,
    val languageTag: String,
    val url: String,
    val isAutoGenerated: Boolean,
)

/**
 * Everything the player needs for one approved video: an optional DASH manifest (multi-track,
 * so quality/audio can be switched through Media3's track APIs) plus progressive fallbacks.
 */
data class ResolvedMedia(
    val videoId: String,
    val title: String,
    val durationMs: Long,
    val dashMpdUrl: String?,
    val qualities: List<QualityOption>,
    val audioOptions: List<AudioOption>,
    val captions: List<CaptionOption>,
) {
    val defaultQuality: QualityOption? get() = qualities.firstOrNull()
    val defaultAudio: AudioOption? get() = audioOptions.firstOrNull()

    /** True when the media exposes several tracks, i.e. real quality/audio selection applies. */
    val isAdaptive: Boolean get() = !dashMpdUrl.isNullOrBlank()
}

/**
 * Resolves an approved video id into playable renditions using NewPipeExtractor.
 * Kept deliberately free of player/UI concerns so it stays unit-testable.
 */
object VideoResolver {

    private const val MAX_HEIGHT = 1080

    suspend fun resolve(videoId: String): ResolvedMedia? = withContext(Dispatchers.IO) {
        try {
            val extractor = ServiceList.YouTube.getStreamExtractor(
                "https://www.youtube.com/watch?v=$videoId"
            )
            extractor.fetchPage()

            val title = runCatching { extractor.name }
                .getOrNull()?.takeIf { it.isNotBlank() } ?: videoId
            val durationMs = runCatching { extractor.length }.getOrDefault(0L) * 1000L
            val dashUrl = runCatching { extractor.dashMpdUrl }
                .getOrNull()?.takeIf { it.isNotBlank() }

            val progressive = runCatching { extractor.videoStreams }.getOrNull().orEmpty()
            val videoOnly = runCatching { extractor.videoOnlyStreams }.getOrNull().orEmpty()
            val audio = runCatching { extractor.audioStreams }.getOrNull().orEmpty()

            val captions = runCatching { extractor.subtitlesDefault }.getOrNull().orEmpty()
                .mapNotNull { sub ->
                    val url = runCatching { sub.content }.getOrNull()
                        ?.takeIf { it.isNotBlank() } ?: return@mapNotNull null
                    val tag = runCatching { sub.languageTag }.getOrNull() ?: "und"
                    val name = runCatching { sub.displayLanguageName }.getOrNull()
                    CaptionOption(
                        label = name?.takeIf { it.isNotBlank() } ?: tag,
                        languageTag = tag,
                        url = url,
                        isAutoGenerated = runCatching { sub.isAutoGenerated }.getOrDefault(false),
                    )
                }

            val bestAudio = audio.maxByOrNull { runCatching { it.averageBitrate }.getOrDefault(0) }

            // One option per height: progressive (already muxed) wins, otherwise video+audio.
            val byHeight = LinkedHashMap<Int, QualityOption>()
            progressive.forEach { stream ->
                val height = heightOf(runCatching { stream.resolution }.getOrNull())
                val url = runCatching { stream.content }.getOrNull()
                if (height in 1..MAX_HEIGHT && !url.isNullOrBlank()) {
                    byHeight.putIfAbsent(height, QualityOption(height, "${height}p", url, null, false))
                }
            }
            videoOnly.forEach { stream ->
                val height = heightOf(runCatching { stream.resolution }.getOrNull())
                val url = runCatching { stream.content }.getOrNull()
                val audioUrl = bestAudio?.let { runCatching { it.content }.getOrNull() }
                if (height in 1..MAX_HEIGHT && !url.isNullOrBlank()
                    && !audioUrl.isNullOrBlank() && !byHeight.containsKey(height)
                ) {
                    byHeight[height] = QualityOption(height, "${height}p", url, audioUrl, true)
                }
            }

            val qualities = byHeight.values.sortedByDescending { it.height }
            val audioOptions = audio
                .mapNotNull { stream ->
                    val url = runCatching { stream.content }.getOrNull()
                        ?.takeIf { it.isNotBlank() } ?: return@mapNotNull null
                    val bitrate = runCatching { stream.averageBitrate }.getOrDefault(0)
                    val trackId = runCatching { stream.audioTrackId }.getOrNull()
                        ?.takeIf { it.isNotBlank() } ?: "und"
                    val locale = runCatching { stream.audioLocale }.getOrNull()
                    val languageTag = locale?.language
                        ?: trackId.substringBefore('.').takeIf { it.length in 2..5 }
                        ?: "und"
                    val trackName = runCatching { stream.audioTrackName }.getOrNull()
                        ?.takeIf { it.isNotBlank() }
                    val typeName = runCatching { stream.audioTrackType.toString() }.getOrDefault("")
                    AudioOption(
                        label = trackName ?: locale?.displayLanguage ?: "Original",
                        url = url,
                        bitrateKbps = bitrate,
                        trackId = trackId,
                        languageTag = languageTag,
                        isAutoDubbed = typeName.contains("DUBBED_AUTO"),
                    )
                }
                .groupBy { it.trackId }                                   // one option per language
                .mapNotNull { (_, variants) -> variants.maxByOrNull { it.bitrateKbps } }
                .sortedByDescending { it.bitrateKbps }

            if (qualities.isEmpty()) {
                AppLogger.error("No playable stream for $videoId")
                return@withContext null
            }

            AppLogger.log(
                "Resolved $videoId: ${qualities.size} qualities, ${audioOptions.size} audio, " +
                    "${captions.size} captions, dash=${!dashUrl.isNullOrBlank()}"
            )

            ResolvedMedia(
                videoId = videoId,
                title = title,
                durationMs = durationMs,
                dashMpdUrl = dashUrl,
                qualities = qualities,
                audioOptions = audioOptions,
                captions = captions,
            )
        } catch (e: Exception) {
            AppLogger.error("Resolution failed for $videoId: ${e.message}")
            null
        }
    }

    /** "1080p" / "720p60" -> 1080 / 720 (leading digits only). */
    internal fun heightOf(resolution: String?): Int {
        if (resolution.isNullOrBlank()) return 0
        return Regex("^(\\d+)").find(resolution.trim())?.groupValues?.get(1)?.toIntOrNull() ?: 0
    }
}
